import { useState } from "react";
import DownloadSection from "../components/download_section";
import Footer from "../components/footer";
import Navbar from "../components/navbar";

import ApplePlayImg from "../assets/apple_store_img.png";
import GooglePlayImg from "../assets/google_play_img.png";
import iPhoneScreenReferral from "../assets/iphone_screen_referral.png";
import RefferalDone from "../assets/refferal_done.png";
import RefferalGroup from "../assets/refferal_group_image.png";
import RefferalGroupHand from "../assets/referral_rules_hand.png";
import ReferralIcon1 from "../assets/referral_icon_1.png";
import ReferralIcon2 from "../assets/referral_icon_2.png";
import ReferralIconStaking from "../assets/referral_staking_color.png";
import ReferralIcon4 from "../assets/referral_icon_4.png";
import ReferralMorflax from "../assets/morflax-studio-175.png";
import ReferralRulesExplain from "../assets/referral_rules_explain.png";
import ArrowRight from "../assets/Right.png";

export default function Referral() {
  const [explain, setRuleExplain] = useState(false);
  const [activeItem, setActiveItem] = useState(null);

  const handleItemClick = (index) => {
    setActiveItem(index === activeItem ? null : index);
  };

  const items = [
    {
      title: "How do I participate in the referral program?",
      content: "Content for Item 1",
    },
    {
      title: "What are the requirements to receive a reward?",
      content: "Content for Item 2",
    },
    {
      title: "How much of a reward can I receive?",
      content: "Content for Item 2",
    },
    {
      title: "How long will I receive rewards for my referrals?",
      content: "Content for Item 2",
    },
    {
      title: "Can I refer multiple users?",
      content: "Content for Item 2",
    },
    {
      title: "Can I refer multiple users?",
      content: "Content for Item 2",
    },
    {
      title: "Can I refer multiple users?",
      content: "Content for Item 2",
    },
  ];

  return (
    <>
      <Navbar />
      {/* <div class="mt-3 mx-auto px-2 sm:px-6 lg:px-8 h-18"> */}
        <div className="center-container-alt">
          <div className="career-section airdrop-section flex flex-col mt-24 sh-p-12-alt-n relative md:pt-8 md:pb-8 md:pr-20 md:pl-20 lg:pt-24 lg:pb-24 lg:pr-80 lg:pl-80">

          {/* <div className="career-section airdrop-section sh-p-12-alt-n overflow-hidden mt-24 grid justify-center"> */}
            <div className="max-w-4xl flex flex-col mx-auto my-auto justify-center items-center">
              <div className="text-white text-center px-4">
                <div className="flex flex-col h-full">
                  <h4
                    className="items-center justify-center referral-banner-header"
                  >
                    Share and Earn
                  </h4>
                  <p
                    className="text-md md:text-xl lg:text-2xl mt-2 whitespace-pre-line referral-banner-sub"
                  >
                    The rewards for this referral program are based on a
                    percentage of the fees generated by the new user. The referrer
                    will receive 90% of the fees generated by their referral
                  </p>
                  <div className="flex mt-8 items-center justify-center">
                    <a
                      href="https://www.apple.com/app-store/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="mr-4"
                    >
                      <img
                        src={ApplePlayImg}
                        alt="Download on Apple Store"
                        className="h-16"
                      />
                    </a>
                    <a
                      href="https://play.google.com/store"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <img
                        src={GooglePlayImg}
                        alt="Download on Google Play Store"
                        className="h-16"
                      />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex justify-center items-center">
          <div
            className="relative rounded-sm overflow-hidden mt-12 grid mb-12"
            style={{ maxWidth: "65%" }}
          >
            <h3 className="text-md text-center justify-center md:text-2xl lg:text-4xl">
              Rules for a referral program
            </h3>

            <div className=" grid grid-cols-2 gap-4 mt-8">
              <div className="grid grid-cols-2 gap-4">
                <div
                  className="flex justify-center items-center flex-col pt-4 pl-4 pr-4 referral-rules-section-1"
                >
                  <div className="relative">
                    <p
                      className="referral-rules-section-1-text"
                    >
                      Users must have an{" "}
                      <span className="referral-program-sub-text-color">
                        active account
                      </span>{" "}
                      with the platform
                    </p>
                  </div>

                  <div className="relative mt-4 flex-grow-0">
                    <img
                      className="mx-auto mt-auto"
                      src={iPhoneScreenReferral}
                      alt="Iphone Screen"
                    />
                  </div>
                </div>

                <div
                  className="flex flex-col  pt-4 pl-4 pr-4 referral-rules-section-1"
                >
                  <div className="relative">
                    <img
                      className="mx-auto mt-auto"
                      src={RefferalDone}
                      alt="Referral Done"
                    />
                  </div>
                  <div className="relative mb-2">
                    <p
                      className="referral-rules-section-1-text"
                    >
                      Each user will be given a{" "}
                      <span className="referral-program-sub-text-color">
                        unique referral code
                      </span>
                    </p>
                  </div>
                  <div className="relative mx-auto mt-auto flex-grow">
                    <p
                      className="referral-rules-section-1-text-small"
                    >
                      that they can share with their friends, family, and
                      colleagues.
                    </p>
                  </div>
                </div>
              </div>
              <div>
                <div
                  className="flex flex-col  pt-4 pr-4 referral-rules-section-1"
                >
                  <div className="relative mb-8 pb-8 pt-8 mt-8">
                    <img
                      className="mx-auto mt-auto"
                      src={RefferalGroup}
                      alt="Referral Done"
                    />
                  </div>
                  <div className="relative pl-6">
                    <p
                      className="referral-rules-section-1-text"
                      style={{
                        width: "15.375rem",
                      }}
                    >
                      The reward will be based on the{" "}
                      <span className="referral-program-sub-text-color">
                        activities
                      </span>
                    </p>
                  </div>
                  <div className="relative pl-6 mb-4">
                    <p
                      className="referral-rules-section-1-text-small"
                    >
                      of the new user and may change over time.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex gap-4 mt-8">
              <div
                className="flex-auto w-64 referral-rules-section-2"
              >
                <div className="relative">
                  <div className="flex flex-row relative">
                    <div className="ml-6 mt-4 pt-4 mr-6 pr-6 gap-4 pb-4">
                      <p className="text-base w-72 font-semibold text-white leading-6">
                        New users must sign up using the referral code in order
                        to be{" "}
                        <span className="referral-program-sub-text-color">
                          counted as a referral
                        </span>
                      </p>
                      <p className="text-sm w-80 font-light text-white leading-5">
                        The referrer will only receive a reward if the new user
                        completes one of the following actions:
                      </p>
                    </div>
                    <div className="absolute right-0">
                      <img src={RefferalGroupHand} alt="Referral Group Hand" />
                    </div>
                  </div>
                  <div className="flex flex-row gap-4 mb-4 pb-4 pl-2 ml-2 w-80">
                    <div className="flex flex-col">
                      <div>
                        <img src={ReferralIcon1} alt="Referral Icon 1" />
                      </div>
                      <div>
                        <p className="text-sm font-light text-white leading-5">
                          Trades on the platform
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-col">
                      <div>
                        <img src={ReferralIcon2} alt="Referral Icon 2" />
                      </div>
                      <div>
                        <p className="text-sm font-light text-white leading-5">
                          Deposits funds into an index
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-col">
                      <div>
                        <img
                          src={ReferralIconStaking}
                          alt="Referral Icon Staking"
                        />
                      </div>
                      <div>
                        <p className="text-sm font-light text-white leading-5">
                          Stakes their assets
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex-auto w-32 h-72">
                <div
                  className="flex flex-col referral-rules-section-1"
                >
                  <div className="grid grid-cols-2">
                    <div className="ml-4 mt-4 pt-4 pl-4">
                      <img
                        className="mt-auto mr-2"
                        src={ReferralIcon4}
                        alt="Referral Icon 4"
                      />
                    </div>
                    <div>
                      <img
                        className="mt-auto h-40"
                        src={ReferralMorflax}
                        alt="Referral Icon 4"
                      />
                    </div>
                  </div>

                  <div className="flex flex-col m-4">
                    <div className="relative mb-2 pl-6">
                      <p
                        className="referral-rules-section-1-text"
                      >
                        The platform reserves the right to modify these rules at
                        any time{" "}
                        <span className="referral-program-sub-text-color">
                          without prior notice
                        </span>
                      </p>
                    </div>
                    <div className="relative pl-6 mb-4">
                      <p
                      className="referral-rules-section-1-text-small"
                      >
                        By participating in the referral program, users agree to
                        these rules and any future changes.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className=" grid grid-cols-3 gap-4 mt-8">
              <div
                className="referral-rules-section-3"
              >
                <p
                  className="referral-rules-section-1-text-small"
                >
                  The referral program is subject to change or termination at
                  any time at the discretion of the platform
                </p>
              </div>
              <div
                className="referral-rules-section-3"
              >
                <p
                  className="referral-rules-section-1-text-small"
                >
                  The platform reserves the right to void rewards or take other
                  appropriate action if it detects fraudulent or abusive
                  behavior
                </p>
              </div>

              <div
                className="referral-rules-section-3"
              >
                <p
                  className="referral-rules-section-1-text-small"
                >
                  Users are responsible for complying with all applicable laws
                  and regulations related to the referral program
                </p>
              </div>
            </div>

            {!explain ? (
              <div className="flex gap-4 mt-8">
                <div
                  className="flex justify-center items-center referral-rules-explain-section"
                  onClick={() => setRuleExplain(true)}
                >
                  <p
                    className="referral-rules-explain-section-text"
                  >
                    Explanation of reward system{" "}
                  </p>
                  <img
                    className="referral-rules-explain-section-arrow-img"
                    src={ArrowRight}
                    alt="Icon Arrow Right"
                  />
                </div>
              </div>
            ) : (
              <div className="flex gap-4 mt-8">
                <div className="flex-auto w-28 ">
                  <div
                    className="flex flex-col referral-rules-section-1"
                  >
                    <div className="flex">
                      <img
                        className="mt-auto"
                        src={ReferralRulesExplain}
                        alt="Referral Icon 4"
                      />
                    </div>
                  </div>
                </div>
                <div
                  className="flex-auto w-64 referral-rules-explain-section-details"
                >
                  <div className="relative">
                    <div className="flex flex-col">
                      <div className="ml-6 mt-4 pt-4 mr-6 pr-6 gap-4 pb-4">
                        <h3 className="mb-2">Explanation of reward system</h3>
                        <p className="text-sm mb-2 font-light leading-5">
                          The rewards for this referral program are based on a
                          percentage of the fees generated by the new user. The
                          referrer will receive 90% of the fees generated by
                          their referral.
                        </p>
                        <p className="text-sm font-light mb-2 leading-5">
                          For example, if a new user generates $100 in fees
                          through trading, depositing into indexes, or staking,
                          the referrer will receive $90 as a reward.{" "}
                        </p>
                        <p className="text-sm font-light mb-2 leading-5">
                          It's important to note that the actual amount of the
                          reward may vary depending on the activities of the new
                          user and may be subject to change. The referrer should
                          periodically check the terms and conditions of the
                          referral program for any updates.{" "}
                        </p>

                        <p className="text-sm font-light mb-2 leading-5">
                          The referral rewards will be awarded to the referrer
                          for the life of the app or until the referral program
                          is terminated by the platform. This means that as long
                          as the new user continues to generate fees through
                          trading, depositing into indexes, or staking, the
                          referrer will continue to receive a percentage of the
                          fees.{" "}
                        </p>

                        <p className="text-sm font-light mb-2 leading-5">
                          It's important to note that the platform reserves the
                          right to terminate the referral program at any time,
                          without prior notice. In such an event, the referrer
                          will no longer be eligible for rewards.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
        <div className="faq">
          <div
            className="mx-auto pl-32 pr-32 pt-16 pb-32"
            style={{ width: "70%" }}
          >
            <h3 className="text-md md:text-2xl lg:text-4xl text-center mb-4">
              FAQ
            </h3>
            {items.map((item, index) => (
              <div key={index} className="faq-items shadow-md rounded-lg mb-4">
                <div
                  className="flex items-center justify-between p-3 cursor-pointer"
                  onClick={() => handleItemClick(index)}
                >
                  <h3 className="text-lg font-medium">{item.title}</h3>
                  <svg
                    className={`w-5 h-5 transition-transform ${
                      index === activeItem ? "transform rotate-180" : ""
                    }`}
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path fillRule="evenodd" d="M6 8l4 4 4-4" />
                  </svg>
                </div>
                {index === activeItem && (
                  <div className="p-3">{item.content}</div>
                )}
              </div>
            ))}

            <div className="flex faqs-other-questions">
              <p className="faqs-other-questtions-txt">Have other questions?</p>
              {/* <button className="">Ask a Question</button> */}
            </div>
          </div>
        </div>
        <DownloadSection />
      {/* </div> */}
      <Footer />
    </>
  );
}
