// import ReferralBackgroundImg from "../assets/referral-share-earn.png"
import ApplePlayImg from "../assets/apple_store_img.png"
import GooglePlayImg from "../assets/google_play_img.png"

export default function ReferralShareEarn() {
  return (
    <div className="share-earn-banner overflow-hidden mt-8  grid justify-center">
      {/* <img
        className="w-full h-auto"
        src={ReferralBackgroundImg}
        alt="Background"
      /> */}
    
      {/* <div className="absolute max-w-4xl place-items-center top-1.5 left-1.5 flex flex-col "> */}
      <div className="max-w-4xl flex flex-col mx-auto my-auto p-24 justify-center items-center">
        <div className="text-white text-center px-4">
        <div className="flex flex-col h-full">
          <h4 
            className="items-center justify-center"
            style={{
                color: "#FFF",
                textAlign: "center",
                fontSize: "4rem",
                fontFamily: "Satoshi",
                fontWeight: 500,
                lineHeight: "4rem"
            }}
            >
            Share and Earn
          </h4>
          <p className="text-md md:text-xl lg:text-2xl mt-2 whitespace-pre-line">
            The rewards for this referral program are based on a percentage of the fees generated by the new user. The referrer will receive 90% of the fees generated by their referral
          </p>
          <div className="flex mt-4 items-center justify-center">
            <a
              href="https://www.apple.com/app-store/"
              target="_blank"
              rel="noopener noreferrer"
              className="mr-4"
            >
              <img
                src={ApplePlayImg}
                alt="Download on Apple Store"
                className="h-12"
              />
            </a>
            <a
              href="https://play.google.com/store"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img
                src={GooglePlayImg}
                alt="Download on Google Play Store"
                className="h-12"
              />
            </a>
          </div>
          </div>
        </div>
      </div>
    </div>
  )
}

